spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie
    username: Alex
    password : 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

server:
  port: 8080